In [1]:
import pandas as pd

In [147]:
import numpy as np

In [175]:
df = pd.read_csv('data.csv')

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [177]:
df['Title'] = df['Name'].str.extract('(Mrs|Mr|Miss|Master)')

In [178]:
df = df[['PassengerId', 'Name', 'Age', 'Sex', 'Title', 'SibSp', 'Parch', 'Ticket', 'Embarked', 'Cabin', 'Fare', 'Embarked', 'Survived' ]]

#c - executiVA, S - padrão, q - com tarifa promocional

In [179]:
df.fillna('Nulo').head(20)

,PassengerId,Name,Age,Sex,Title,SibSp,Parch,Ticket,Embarked,Cabin,Fare,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",22.0,male,Mr,1,0,A/5 21171,S,Nulo,7.2500,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,female,Mrs,1,0,PC 17599,C,C85,71.2833,C,1
2,3,"Heikkinen, Miss. Laina",26.0,female,Miss,0,0,STON/O2. 3101282,S,Nulo,7.9250,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,female,Mrs,1,0,113803,S,C123,53.1000,S,1
4,5,"Allen, Mr. William Henry",35.0,male,Mr,0,0,373450,S,Nulo,8.0500,S,0
5,6,"Moran, Mr. James",Nulo,male,Mr,0,0,330877,Q,Nulo,8.4583,Q,0
6,7,"McCarthy, Mr. Timothy J",54.0,male,Mr,0,0,17463,S,E46,51.8625,S,0
7,8,"Palsson, Master. Gosta Leonard",2.0,male,Master,3,1,349909,S,Nulo,21.0750,S,0
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",27.0,female,Mrs,0,2,347742,S,Nulo,11.1333,S,1
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",14.0,female,Mrs,1,0,237736,C,Nulo,30.0708,C,1
10,11,"Sandstrom, Miss. Marguerite Rut",4.0,female,Miss,1,1,PP 9549,S,G6,16.7000,S,1
11,12,"Bonnell, Miss. Elizabeth",58.0,female,Miss,0,0,113783,S,C103,26.5500,S,1
12,13,"Saundercock, Mr. William Henry",20.0,male,Mr,0,0,A/5. 2151,S,Nulo,8.0500,S,0
13,14,"Andersson, Mr. Anders Johan",39.0,male,Mr,1,5,347082,S,Nulo,31.2750,S,0
14,15,"Vestrom, Miss. Hulda Amanda Adolfina",14.0,female,Miss,0,0,350406,S,Nulo,7.8542,S,0
15,16,"Hewlett, Mrs. (Mary D Kingcome)",55.0,female,Mrs,0,0,248706,S,Nulo,16.0000,S,1
16,17,"Rice, Master. Eugene",2.0,male,Master,4,1,382652,Q,Nulo,29.1250,Q,0
17,18,"Williams, Mr. Charles Eugene",Nulo,male,Mr,0,0,244373,S,Nulo,13.0000,S,1
18,19,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",31.0,female,Mrs,1,0,345763,S,Nulo,18.0000,S,0
19,20,"Masselmani, Mrs. Fatima",Nulo,female,Mrs,0,0,2649,C,Nulo,7.2250,C,1

In [193]:
df[df['Sex'].isin(['female'])]

,PassengerId,Name,Age,Sex,Title,SibSp,Parch,Ticket,Embarked,Cabin,Fare,Embarked,Survived
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,female,Mrs,1,0,PC 17599,C,C85,71.2833,C,1
2,3,"Heikkinen, Miss. Laina",26.0,female,Miss,0,0,STON/O2. 3101282,S,NaN,7.9250,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,female,Mrs,1,0,113803,S,C123,53.1000,S,1
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",27.0,female,Mrs,0,2,347742,S,NaN,11.1333,S,1
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",14.0,female,Mrs,1,0,237736,C,NaN,30.0708,C,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,"Shelley, Mrs. William (Imanita Parrish Hall)",25.0,female,Mrs,0,1,230433,S,NaN,26.0000,S,1
882,883,"Dahlberg, Miss. Gerda Ulrika",22.0,female,Miss,0,0,7552,S,NaN,10.5167,S,0
885,886,"Rice, Mrs. William (Margaret Norton)",39.0,female,Mrs,0,5,382652,Q,NaN,29.1250,Q,0
887,888,"Graham, Miss. Margaret Edith",19.0,female,Miss,0,0,112053,S,B42,30.0000,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,female,Miss,1,2,W./C. 6607,S,NaN,23.4500,S,0