In [ ]:
import pandas as pd

In [7]:
df = pd.read_csv('iris.csv')

In [8]:
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [9]:
df = pd.read_json('empresa_clientes.json')

In [10]:
df

,_id,nome,email,telefone,endereco,ativo
0,{'$oid': '68a8ded8751ba2a28374a8ff'},Ana Souza,ana.souza@email.com,11-99999-1234,"{'rua': 'Rua das Flores', 'numero': 123, 'cida...",True
1,{'$oid': '68a8ded8751ba2a28374a900'},Carlos Pereira,carlos.pereira@email.com,21-98888-4321,"{'rua': 'Av. Atlântica', 'numero': 456, 'cidad...",True
2,{'$oid': '68a8ded8751ba2a28374a901'},Fernanda Lima,fernanda.lima@email.com,31-97777-5678,"{'rua': 'Praça da Liberdade', 'numero': 789, '...",False